### ISSUE TITLE
Titlebar text flashing on change

### ISSUE THREAD

**Issue by RickMarijn** [a-parhom/RoundedSBE#1]
When the titlebar text changes, for example when switching tabs in firefox, it starts flashing. But only sometimes. If I ened to give more information just ask me.

**Comment by a-parhom** [comment]
That's an upstream bug: https://bugs.kde.org/show_bug.cgi?id=464417

**Comment by RickMarijn** [comment]
Is there a fix or do I just wait for plasma updates? I can't find anything on fixing the issue on the website you linked.

**Comment by a-parhom** [comment]
It's not been fixed yet, so just wait.

**Comment by RickMarijn** [comment]
Alr, ty

**Comment by a-parhom** [comment]
Going to be fixed in Plasma 5.27.1: https://invent.kde.org/plasma/kwin/-/merge_requests/3634

**Comment by toxic-candy** [comment]
Fixed with Plasma 5.27.1
