### ISSUE TITLE
Do not highlight all buttons.

### ISSUE THREAD

**Issue by developer91234** [a-parhom/RoundedSBE#10]
When you hover over a titlebar button, all the buttons get highlighted. This is very non-standard and provides bad feedback. I recommend just normally highlighting whichever button is the mouse is hovering over, instead of all the buttons.

**Comment by a-parhom** [comment]
It has a Unison hovering switch in the config

**Comment by developer91234** [comment]
Thanks, found it. Consider disabling unison by default, unless it's your preference.
