### ISSUE TITLE
install.sh script complains about not being able to find KF5 IconThemes on fedora kde

### ISSUE THREAD

**Issue by kaem-e** [a-parhom/RoundedSBE#16]
The install script fails on Fedora KDE 38 not being able to find **KF5IconThemes** provided by the `kf5-kiconthemes-devel` package.
 
![image](https://github.com/a-parhom/RoundedSBE/assets/46230985/d4508eeb-ead2-426b-b899-dcac5d4c736e)

The solution is obviously to just `dnf install f5-kiconthemes-devel`, perhaps add this in the Build dependencies section for fedora in README.md ?

**Comment by a-parhom** [comment]
Fixed in 4f71ab0.
