### ISSUE TITLE
Corners shader crashes Plasma Wayland with dual-monitor setup

### ISSUE THREAD

**Issue by Jorma17** [a-parhom/RoundedSBE#3]
When I have the desktop effect enabled that rounds the bottom corners, plug in my external monitor and try to drag any app into it, both screens go black and all apps crash. This only happens on Wayland with the KWin script enabled.

I made a KDE bug report (I thought it was a KWin issue):
https://bugs.kde.org/show_bug.cgi?id=466430

When I disable the corner shader, everything works just fine. I have recompiled the latest version against Plasma 5.27.2 and the issue persists.

**Comment by a-parhom** [comment]
Can't reproduce this with Plasma 5.27.2.

**Comment by gabelluardo** [comment]
I have the same issue with a dual monitor setup on wayland. The workaround is disabling the corner shader, but I prefer the rounded corener for sure. @a-parhom if you have any idea of what the issue can be and which file I have to see, maybe I can work on a fix
