### ISSUE TITLE
displacement of buttons upon maximize

### ISSUE THREAD

**Issue by JayCeeCreates** [a-parhom/RoundedSBE#4]
so this happens everytime i maximize a window

![image](https://user-images.githubusercontent.com/28774264/223110075-88089662-a712-48d1-b7a9-8b614f228cae.png)

seems like the close button ain't being paid enough lol
well, not just the close button, but also any other button being placed on the left side

![image](https://user-images.githubusercontent.com/28774264/223111645-9ddc038d-3ce2-47b4-9251-a2646b13a6d6.png)

anyways i hope for a quick patch soon-

**Comment by a-parhom** [comment]
Possible solution: https://github.com/kupiqu/SierraBreezeEnhanced/issues/111#issuecomment-1345371018
